management:
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: true
          base-url: http://localhost:9091
          push-rate: 30s
          job: hello-job
          grouping-key:
            app-name: my-batch
          shutdown-operation: push
